import io
import html
from datetime import datetime
from typing import List

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable,
)
from reportlab.pdfgen import canvas

from analyze_contract import ContractAnalysisResult, ClauseAnalysis


def safe_text(text: str) -> str:
    """Escapes HTML/XML entities to prevent ReportLab XML parsing errors."""
    if not text:
        return ""
    return html.escape(str(text).strip())


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and stamp total page count,
    running header (pages 2+) and confidential running footer.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(HexColor("#64748B"))

        # Running Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(36, 756, "LegalDoc.AI — Contract Risk Assessment & Consultation Brief")
            self.drawRightString(612 - 36, 756, datetime.now().strftime("%B %d, %Y"))
            self.setStrokeColor(HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(36, 748, 612 - 36, 748)

        # Running Footer (all pages)
        self.setStrokeColor(HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(36, 36, 612 - 36, 36)

        self.setFont("Helvetica", 7.5)
        self.setFillColor(HexColor("#64748B"))
        self.drawString(
            36,
            24,
            "CONFIDENTIAL • Generated by LegalDoc.AI for informational guidance only; does not constitute formal legal advice.",
        )
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.setFont("Helvetica-Bold", 8)
        self.drawRightString(612 - 36, 24, page_str)
        self.restoreState()


def get_risk_colors(risk_level: str):
    """Returns (bg_color, text_color, border_color) for a risk level."""
    level = (risk_level or "LOW").upper()
    if level == "CRITICAL":
        return HexColor("#FEE2E2"), HexColor("#991B1B"), HexColor("#EF4444")
    elif level == "HIGH":
        return HexColor("#FEF3C7"), HexColor("#92400E"), HexColor("#F59E0B")
    elif level == "MEDIUM":
        return HexColor("#FEF9C3"), HexColor("#854D0E"), HexColor("#EAB308")
    else:  # LOW
        return HexColor("#DCFCE7"), HexColor("#166534"), HexColor("#22C55E")


def generate_report_pdf(analysis: ContractAnalysisResult) -> io.BytesIO:
    """
    Generates a professional, multi-page executive contract assessment PDF.
    Returns an in-memory BytesIO buffer containing the PDF binary.
    """
    buffer = io.BytesIO()

    # Page size: Letter (612 x 792 pt), margins: 36pt (0.5 in) left/right, 40pt top/bottom
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=42,
        bottomMargin=46,
    )

    styles = getSampleStyleSheet()

    # Custom Typography Hierarchy
    style_title = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=HexColor("#0F172A"),
    )

    style_subtitle = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13,
        textColor=HexColor("#475569"),
    )

    style_section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=HexColor("#1E293B"),
        spaceBefore=14,
        spaceAfter=6,
    )

    style_meta_label = ParagraphStyle(
        "MetaLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=11,
        textColor=HexColor("#64748B"),
    )

    style_meta_val = ParagraphStyle(
        "MetaVal",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=HexColor("#0F172A"),
    )

    style_body = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=HexColor("#1E293B"),
    )

    style_clause_title = ParagraphStyle(
        "ClauseTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=13,
        textColor=HexColor("#0F172A"),
    )

    style_clause_badge = ParagraphStyle(
        "ClauseBadge",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=10,
        alignment=TA_RIGHT,
    )

    style_clause_label = ParagraphStyle(
        "ClauseSubLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=7.5,
        leading=10,
        textColor=HexColor("#475569"),
    )

    style_original_text = ParagraphStyle(
        "OriginalText",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=8,
        leading=11,
        textColor=HexColor("#334155"),
    )

    style_redline = ParagraphStyle(
        "RedlineText",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=HexColor("#1E1B4B"),
    )

    style_tip = ParagraphStyle(
        "TipText",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=HexColor("#0F766E"),
    )

    style_disclaimer = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=7.5,
        leading=10.5,
        textColor=HexColor("#64748B"),
        alignment=TA_CENTER,
    )

    story = []

    # =========================================================================
    # 1. Document Header & Brand
    # =========================================================================
    header_table = Table(
        [
            [
                Paragraph("<b>LegalDoc.AI</b>", style_title),
                Paragraph(
                    f"<b>Report Generated:</b> {datetime.now().strftime('%B %d, %Y')}<br/>"
                    f"<b>Assessment Engine:</b> v1.0.0 (Gemini)",
                    ParagraphStyle(
                        "HeaderRight",
                        parent=styles["Normal"],
                        fontName="Helvetica",
                        fontSize=8,
                        leading=11,
                        textColor=HexColor("#64748B"),
                        alignment=TA_RIGHT,
                    ),
                ),
            ],
            [
                Paragraph(
                    "CONTRACT RISK ASSESSMENT & CONSULTATION BRIEF",
                    ParagraphStyle(
                        "HeaderTagline",
                        parent=style_subtitle,
                        fontName="Helvetica-Bold",
                        fontSize=9,
                        leading=12,
                        textColor=HexColor("#4F46E5"),
                    ),
                ),
                "",
            ],
        ],
        colWidths=[360, 180],
    )
    header_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    story.append(header_table)
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=1.5, color=HexColor("#4F46E5"), spaceAfter=10))

    # =========================================================================
    # 2. Document Metadata Card
    # =========================================================================
    parties_str = ", ".join(analysis.parties_involved) if analysis.parties_involved else "None identified"
    meta_data = [
        [
            Paragraph("DOCUMENT TITLE", style_meta_label),
            Paragraph("PARTIES IDENTIFIED", style_meta_label),
            Paragraph("TOTAL CLAUSES EVALUATED", style_meta_label),
        ],
        [
            Paragraph(safe_text(analysis.document_title), style_meta_val),
            Paragraph(safe_text(parties_str), style_meta_val),
            Paragraph(f"{len(analysis.clauses)} Clauses", style_meta_val),
        ],
    ]
    meta_table = Table(meta_data, colWidths=[230, 210, 100])
    meta_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), HexColor("#F8FAFC")),
                ("BOX", (0, 0), (-1, -1), 0.75, HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # =========================================================================
    # 3. Overall Risk Banner
    # =========================================================================
    score = analysis.overall_risk_score
    if score >= 75:
        risk_tier = "CRITICAL RISK — PREDATORY / UNBALANCED TERMS"
        banner_bg = HexColor("#991B1B")
    elif score >= 50:
        risk_tier = "HIGH RISK — SIGNIFICANT CONTRACTUAL EXPOSURE"
        banner_bg = HexColor("#D97706")
    elif score >= 25:
        risk_tier = "MODERATE RISK — CAUTION ADVISED"
        banner_bg = HexColor("#CA8A04")
    else:
        risk_tier = "LOW RISK — STANDARD / BALANCED AGREEMENT"
        banner_bg = HexColor("#16A34A")

    risk_banner_content = [
        [
            Paragraph(
                f"<font size=12><b>OVERALL RISK SCORE: {score}/100</b></font><br/>"
                f"<font size=9><b>{risk_tier}</b></font>",
                ParagraphStyle(
                    "RiskBannerText",
                    parent=styles["Normal"],
                    fontName="Helvetica-Bold",
                    textColor=colors.white,
                    alignment=TA_CENTER,
                    leading=15,
                ),
            )
        ]
    ]
    risk_banner_table = Table(risk_banner_content, colWidths=[540])
    risk_banner_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), banner_bg),
                ("BOX", (0, 0), (-1, -1), 1, banner_bg),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ]
        )
    )
    story.append(risk_banner_table)
    story.append(Spacer(1, 12))

    # =========================================================================
    # 4. Section 1: Executive Assessment Summary
    # =========================================================================
    story.append(Paragraph("1. Executive Assessment Summary", style_section_heading))
    summary_table = Table(
        [[Paragraph(safe_text(analysis.risk_summary), style_body)]],
        colWidths=[540],
    )
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), HexColor("#F1F5F9")),
                ("BOX", (0, 0), (-1, -1), 0.75, HexColor("#CBD5E1")),
                ("LINEBEFORE", (0, 0), (0, -1), 3.5, HexColor("#4F46E5")),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ]
        )
    )
    story.append(summary_table)
    story.append(Spacer(1, 14))

    # =========================================================================
    # 5. Section 2: Flagged Clauses Breakdown
    # =========================================================================
    story.append(Paragraph("2. Detailed Clause-by-Clause Evaluation", style_section_heading))
    story.append(
        Paragraph(
            "Each clause has been analyzed for contractual asymmetry, translated into plain English, "
            "and paired with a balanced counter-proposal redline.",
            style_subtitle,
        )
    )
    story.append(Spacer(1, 8))

    for idx, clause in enumerate(analysis.clauses, start=1):
        bg_col, text_col, border_col = get_risk_colors(clause.risk_level)

        clause_rows = [
            # Row 0: Clause Header (Title + Risk Badge)
            [
                Paragraph(
                    f"<b>Clause {idx}: {safe_text(clause.clause_title)}</b> "
                    f"<font color='#64748B' size=7.5>({safe_text(clause.clause_id)})</font>",
                    style_clause_title,
                ),
                Paragraph(
                    f"<b>{safe_text(clause.risk_level)} RISK</b>",
                    ParagraphStyle(
                        "RiskBadge",
                        parent=style_clause_badge,
                        textColor=text_col,
                    ),
                ),
            ],
            # Row 1: Original Legalese
            [
                Paragraph(
                    f"<font color='#64748B'><b>ORIGINAL LEGALESE:</b></font><br/>"
                    f"&ldquo;{safe_text(clause.original_text)}&rdquo;",
                    style_original_text,
                ),
                "",
            ],
            # Row 2: Plain-English Translation
            [
                Paragraph(
                    f"<font color='#2563EB'><b>PLAIN-ENGLISH MEANING (8th-Grade Reading Level):</b></font><br/>"
                    f"{safe_text(clause.plain_english)}",
                    style_body,
                ),
                "",
            ],
            # Row 3: Risk Assessment Reasoning
            [
                Paragraph(
                    f"<font color='#B91C1C'><b>RISK ANALYSIS & POTENTIAL EXPOSURE:</b></font><br/>"
                    f"{safe_text(clause.risk_reasoning)}",
                    style_body,
                ),
                "",
            ],
            # Row 4: Suggested Redline Counter-Proposal
            [
                Paragraph(
                    f"<font color='#4338CA'><b>BALANCED COUNTER-PROPOSAL (SUGGESTED REDLINE):</b></font><br/>"
                    f"&ldquo;{safe_text(clause.suggested_redline)}&rdquo;",
                    style_redline,
                ),
                "",
            ],
            # Row 5: Negotiation Tip
            [
                Paragraph(
                    f"<font color='#0D9488'><b>NEGOTIATION STRATEGY & TALKING POINT:</b></font><br/>"
                    f"{safe_text(clause.negotiation_tip)}",
                    style_tip,
                ),
                "",
            ],
        ]

        clause_card = Table(clause_rows, colWidths=[430, 110])
        clause_card.setStyle(
            TableStyle(
                [
                    # Span rows across 2 columns for body content
                    ("SPAN", (0, 1), (1, 1)),
                    ("SPAN", (0, 2), (1, 2)),
                    ("SPAN", (0, 3), (1, 3)),
                    ("SPAN", (0, 4), (1, 4)),
                    ("SPAN", (0, 5), (1, 5)),
                    # Backgrounds
                    ("BACKGROUND", (0, 0), (-1, 0), bg_col),
                    ("BACKGROUND", (0, 1), (-1, 1), HexColor("#F8FAFC")),
                    ("BACKGROUND", (0, 4), (-1, 4), HexColor("#EEF2FF")),
                    ("BACKGROUND", (0, 5), (-1, 5), HexColor("#F0FDFA")),
                    # Card Borders
                    ("BOX", (0, 0), (-1, -1), 1, border_col),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
                    # Padding
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )

        story.append(KeepTogether([clause_card, Spacer(1, 10)]))

    # =========================================================================
    # 6. Section 3: Pre-Signing Action Checklist
    # =========================================================================
    if analysis.action_checklist:
        checklist_elements = [
            Paragraph("3. Pre-Signing Action Checklist", style_section_heading),
            Paragraph(
                "Prioritized verification items to complete before executing this contract:",
                style_subtitle,
            ),
            Spacer(1, 6),
        ]

        checklist_rows = []
        for idx, item in enumerate(analysis.action_checklist, start=1):
            checklist_rows.append(
                [
                    Paragraph(f"<b>[ &nbsp; ]</b>", ParagraphStyle("Box", parent=style_body, alignment=TA_CENTER)),
                    Paragraph(f"<b>Item {idx}:</b> {safe_text(item)}", style_body),
                ]
            )

        checklist_table = Table(checklist_rows, colWidths=[36, 504])
        checklist_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), HexColor("#F8FAFC")),
                    ("BOX", (0, 0), (-1, -1), 0.75, HexColor("#CBD5E1")),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )
        checklist_elements.append(checklist_table)
        checklist_elements.append(Spacer(1, 14))
        story.append(KeepTogether(checklist_elements))

    # =========================================================================
    # 7. Section 4: Strategic Questions for Legal Counsel
    # =========================================================================
    if analysis.attorney_prep_questions:
        attorney_elements = [
            Paragraph("4. Strategic Questions for Legal Counsel", style_section_heading),
            Paragraph(
                "If consulting an attorney, bring these targeted questions to optimize consultation time and focus on high-risk liabilities:",
                style_subtitle,
            ),
            Spacer(1, 6),
        ]

        question_rows = []
        for idx, q in enumerate(analysis.attorney_prep_questions, start=1):
            question_rows.append(
                [
                    Paragraph(f"<b>Q{idx}</b>", ParagraphStyle("QNum", parent=style_body, fontName="Helvetica-Bold", textColor=HexColor("#4F46E5"), alignment=TA_CENTER)),
                    Paragraph(safe_text(q), style_body),
                ]
            )

        question_table = Table(question_rows, colWidths=[36, 504])
        question_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), HexColor("#F8FAFC")),
                    ("BOX", (0, 0), (-1, -1), 0.75, HexColor("#CBD5E1")),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )
        attorney_elements.append(question_table)
        attorney_elements.append(Spacer(1, 14))
        story.append(KeepTogether(attorney_elements))

    # =========================================================================
    # 8. Statutory Disclaimer Box
    # =========================================================================
    disclaimer_text = (
        "<b>STATUTORY DISCLAIMER & LIMITATION OF LIABILITY:</b> "
        "This Contract Risk Assessment Report is generated by LegalDoc.AI using artificial intelligence strictly for informational, "
        "educational, and preliminary preparation purposes. LegalDoc.AI is not a law firm, does not provide legal representation, "
        "and this document does not establish an attorney-client relationship. Laws vary significantly across jurisdictions. "
        "Users are strongly urged to consult a licensed attorney prior to executing any binding agreement."
    )
    disclaimer_table = Table([[Paragraph(disclaimer_text, style_disclaimer)]], colWidths=[540])
    disclaimer_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), HexColor("#F1F5F9")),
                ("BOX", (0, 0), (-1, -1), 0.5, HexColor("#CBD5E1")),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ]
        )
    )
    story.append(KeepTogether([disclaimer_table]))

    # Build PDF with two-pass NumberedCanvas
    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer
