import io
from datetime import datetime
from typing import List
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from analyze_contract import ClauseAnalysis


def generate_docx_track_changes(
    document_title: str,
    clauses: List[ClauseAnalysis],
    original_full_text: str = "",
) -> io.BytesIO:
    """
    Generates a Word (.docx) amended agreement with Track-Changes styling:
    - Struck-through deleted terms in red
    - Underlined, highlighted counter-proposals in green
    - Plain-English rationale and negotiation annotations
    """
    doc = Document()

    # Set 0.75 in page margins
    for section in doc.sections:
        section.top_margin = Inches(0.75)
        section.bottom_margin = Inches(0.75)
        section.left_margin = Inches(0.75)
        section.right_margin = Inches(0.75)

    # 1. Document Title Header
    title_p = doc.add_paragraph()
    title_p.paragraph_format.space_before = Pt(0)
    title_p.paragraph_format.space_after = Pt(4)
    clean_title = (document_title or "Agreement").strip().upper()
    title_run = title_p.add_run(f"AMENDED REDLINE AGREEMENT: {clean_title}")
    title_run.font.name = "Calibri"
    title_run.font.size = Pt(17)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(15, 23, 42)  # Slate 900

    # Subtitle / Tagline
    sub_p = doc.add_paragraph()
    sub_p.paragraph_format.space_after = Pt(12)
    sub_run = sub_p.add_run(
        f"Generated by LegalDoc.AI • {datetime.now().strftime('%B %d, %Y')} • Proposed Redline & Counter-Proposal Edition"
    )
    sub_run.font.name = "Calibri"
    sub_run.font.size = Pt(9.5)
    sub_run.font.color.rgb = RGBColor(79, 70, 229)  # Indigo 600
    sub_run.font.bold = True

    # 2. Track Changes Legend Callout Table
    legend_table = doc.add_table(rows=1, cols=1)
    legend_table.autofit = False
    legend_table.columns[0].width = Inches(7.0)
    cell = legend_table.cell(0, 0)
    cell_p = cell.paragraphs[0]
    cell_p.paragraph_format.space_before = Pt(4)
    cell_p.paragraph_format.space_after = Pt(4)

    h_legend = cell_p.add_run("TRACK-CHANGES EDITING LEGEND:\n")
    h_legend.font.name = "Calibri"
    h_legend.font.size = Pt(9.5)
    h_legend.font.bold = True
    h_legend.font.color.rgb = RGBColor(30, 41, 59)

    r_del = cell_p.add_run("• Deletions (Struck-through in Red): ")
    r_del.font.name = "Calibri"
    r_del.font.size = Pt(9)
    r_del.font.bold = True
    r_del.font.color.rgb = RGBColor(71, 85, 105)

    r_del_sample = cell_p.add_run("Original Unbalanced / Predatory Terms\n")
    r_del_sample.font.name = "Calibri"
    r_del_sample.font.size = Pt(9)
    r_del_sample.font.strike = True
    r_del_sample.font.color.rgb = RGBColor(185, 28, 28)

    r_ins = cell_p.add_run("• Additions / Counter-Proposals (Underlined in Green): ")
    r_ins.font.name = "Calibri"
    r_ins.font.size = Pt(9)
    r_ins.font.bold = True
    r_ins.font.color.rgb = RGBColor(71, 85, 105)

    r_ins_sample = cell_p.add_run("Proposed Balanced & Fair Substitute Terms\n")
    r_ins_sample.font.name = "Calibri"
    r_ins_sample.font.size = Pt(9)
    r_ins_sample.font.underline = True
    r_ins_sample.font.bold = True
    r_ins_sample.font.color.rgb = RGBColor(21, 128, 61)

    r_note = cell_p.add_run(
        "Note: This document incorporates proposed amendments into the contractual clauses to facilitate transparent negotiation."
    )
    r_note.font.name = "Calibri"
    r_note.font.size = Pt(8.5)
    r_note.font.italic = True
    r_note.font.color.rgb = RGBColor(100, 116, 139)

    spacer = doc.add_paragraph()
    spacer.paragraph_format.space_before = Pt(8)
    spacer.paragraph_format.space_after = Pt(0)

    # 3. Clauses with Track-Changes Redlining
    for idx, clause in enumerate(clauses, start=1):
        # Section Heading
        h = doc.add_paragraph()
        h.paragraph_format.space_before = Pt(14)
        h.paragraph_format.space_after = Pt(4)
        h.paragraph_format.keep_with_next = True

        h_title = h.add_run(f"SECTION {idx}. {clause.clause_title.upper()}")
        h_title.font.name = "Calibri"
        h_title.font.size = Pt(11.5)
        h_title.font.bold = True
        h_title.font.color.rgb = RGBColor(15, 23, 42)

        risk_label = f" [{clause.risk_level} RISK]"
        h_risk = h.add_run(risk_label)
        h_risk.font.name = "Calibri"
        h_risk.font.size = Pt(9)
        h_risk.font.bold = True
        if clause.risk_level in ["CRITICAL", "HIGH"]:
            h_risk.font.color.rgb = RGBColor(185, 28, 28)
        elif clause.risk_level == "MEDIUM":
            h_risk.font.color.rgb = RGBColor(202, 138, 4)
        else:
            h_risk.font.color.rgb = RGBColor(22, 101, 52)

        # Track Changes Text Block
        tc_p = doc.add_paragraph()
        tc_p.paragraph_format.space_before = Pt(2)
        tc_p.paragraph_format.space_after = Pt(6)

        # 1. Struck-through original term
        del_run = tc_p.add_run(f"\"{clause.original_text.strip()}\" ")
        del_run.font.name = "Calibri"
        del_run.font.size = Pt(10)
        del_run.font.strike = True
        del_run.font.color.rgb = RGBColor(185, 28, 28)  # Red strikethrough

        # 2. Inserted balanced counter-proposal
        ins_run = tc_p.add_run(f"\"{clause.suggested_redline.strip()}\"")
        ins_run.font.name = "Calibri"
        ins_run.font.size = Pt(10)
        ins_run.font.underline = True
        ins_run.font.bold = True
        ins_run.font.color.rgb = RGBColor(21, 128, 61)  # Green underline

        # Explanation & Strategy Callout
        note_p = doc.add_paragraph()
        note_p.paragraph_format.space_before = Pt(0)
        note_p.paragraph_format.space_after = Pt(12)

        exp_tag = note_p.add_run("Rationale & Negotiation Strategy: ")
        exp_tag.font.name = "Calibri"
        exp_tag.font.size = Pt(8.5)
        exp_tag.font.bold = True
        exp_tag.font.color.rgb = RGBColor(100, 116, 139)

        exp_text = note_p.add_run(f"{clause.plain_english} — {clause.negotiation_tip}")
        exp_text.font.name = "Calibri"
        exp_text.font.size = Pt(8.5)
        exp_text.font.italic = True
        exp_text.font.color.rgb = RGBColor(71, 85, 105)

    # 4. Closing Execution Disclaimer
    disc_p = doc.add_paragraph()
    disc_p.paragraph_format.space_before = Pt(20)
    disc_run = disc_p.add_run(
        "CONFIDENTIAL & INFORMATIONAL — Generated automatically by LegalDoc.AI for contract negotiation and redlining purposes. "
        "Does not constitute formal legal representation."
    )
    disc_run.font.name = "Calibri"
    disc_run.font.size = Pt(8)
    disc_run.font.italic = True
    disc_run.font.color.rgb = RGBColor(148, 163, 184)

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer
